# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readFASTQC <- function(library, id, spacer_start, spacer_length, rev, comp, fastqIN) {
    invisible(.Call('_MoPAC_readFASTQC', PACKAGE = 'MoPAC', library, id, spacer_start, spacer_length, rev, comp, fastqIN))
}

readFASTQC_shiny <- function(library, id, spacer_start, spacer_length, rev, comp, fastqIN, shinyF) {
    invisible(.Call('_MoPAC_readFASTQC_shiny', PACKAGE = 'MoPAC', library, id, spacer_start, spacer_length, rev, comp, fastqIN, shinyF))
}

get_quantile <- function(M) {
    .Call('_MoPAC_get_quantile', PACKAGE = 'MoPAC', M)
}

getPValues <- function(genes, sgrnas, values, alpha) {
    .Call('_MoPAC_getPValues', PACKAGE = 'MoPAC', genes, sgrnas, values, alpha)
}

RRA_1tail <- function(genes, sgrnas, values) {
    .Call('_MoPAC_RRA_1tail', PACKAGE = 'MoPAC', genes, sgrnas, values)
}

get_sorted <- function(M) {
    .Call('_MoPAC_get_sorted', PACKAGE = 'MoPAC', M)
}

get_sorted1 <- function(V, size) {
    .Call('_MoPAC_get_sorted1', PACKAGE = 'MoPAC', V, size)
}

